"""
P1 Initialisation — Data Model Definitions
============================================
Centralised data model definitions for the P1 Initialisation module.

This file contains all Pydantic data models used by the
DevelopmentAwareLifePeriodPlanner, ParticipantPoolManager, and related
components, including:

  Life-Period Planner models:
  - GlobalSummary: top-level plan metadata
  - PeriodDateRange: date range for a life period
  - LifePeriod: a single life period with all attributes
  - MilestonePlan: the complete life period plan
  - PlanValidationReport: validation results for a plan
  - TransitionDateHint: a single inferred transition date
  - InferredTemporalConstraints: normalised temporal constraints
  - TransitionDateHints: collection of transition date hints

  Participant Pool models:
  - DateOfBirth: structured date-of-birth
  - LocationInfo: geographic location
  - SelfSystemAnchor: value anchor
  - InteractionRecord: a single interaction record
  - Participant: full participant profile
  - Phase1BasicInfo: Phase-1 LLM output (basic identity)
  - Phase1ParticipantList: Phase-1 LLM output (participant list)
  - Phase2TemporalBriefs: Phase-2 LLM output (temporal briefs)
  - Phase3FullProfile: Phase-3 LLM output (extended profile)
  - Phase4SingleMemory: Phase-4 LLM output (single memory)
  - Phase4InitialMemories: Phase-4 LLM output (initial memories)
  - Phase5ConsistencyResult: Phase-5 LLM output (consistency check)
"""

from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field, field_validator


# ==========================================
# Life-Period Planner Data Structures
# ==========================================

class GlobalSummary(BaseModel):
    target_age_exact: int = Field(..., description="Final age of the target person")
    total_periods: int = Field(..., description="Total number of life stages")
    planning_logic: str = Field(..., description="One-sentence summary of the underlying logic of the overall life plan (e.g., from an early family environment emphasizing learning to career convergence in frontier AI)")

class PeriodDateRange(BaseModel):
    start_date: str = Field(..., description="Stage start date, ISO format YYYY-MM-DD")
    end_date: str = Field(..., description="Stage end date, ISO format YYYY-MM-DD")

class LifePeriod(BaseModel):
    period_id: str = Field(..., description="Stage ID, e.g. 'LP1', 'LP2'")
    stage_label: str = Field(..., description="A semantic stage label auto-generated by the model (snake_case format), summarizing the core nature of this stage. E.g., 'early_childhood', 'undergraduate_exploration', 'phd_research_pivot', 'career_entry_adaptation'. For life gap/transition periods, must use 'gap_transition'. Labels should reflect the actual content of the stage, not apply fixed developmental psychology categories.")
    title: str = Field(..., description="A life summary title for this stage")
    dominant_theme: str = Field(..., description="The core organizing logic and dominant theme of this stage")
    developmental_tasks: List[str] = Field(..., description="Developmental tasks that need to be accomplished in this stage")
    stage_goals: List[str] = Field(..., description="What goals the working self tends to organize around in this stage")
    salient_pressures: List[str] = Field(..., description="Typical pressures faced in this stage")
    salient_opportunities: List[str] = Field(..., description="Opportunity windows that converge toward the target persona")
    likely_transition_triggers: List[str] = Field(..., description="Events most likely to push this stage into the next stage")
    period_date_range: PeriodDateRange = Field(..., description="The precise date closed interval for this stage (year-month-day, inclusive)")

    # ── Stage type tags (generated by P1 LLM, consumed by TC Engine) ──
    is_education_stage: bool = Field(
        False,
        description=(
            "Whether this period involves education/learning activities "
            "(kindergarten, school, university, graduate, doctoral, etc.). "
            "A period can be both education and work (e.g., PhD with research work)."
        )
    )
    is_work_stage: bool = Field(
        False,
        description=(
            "Whether this period involves work/career activities "
            "(internship, full-time job, research work, entrepreneurship, etc.). "
            "PhD periods with research work should be marked as both education and work."
        )
    )
    is_transition_stage: bool = Field(
        False,
        description=(
            "Whether this period is a transition/gap period "
            "(waiting for enrollment, gap between graduation and employment, career change buffer, etc.). "
            "Periods with stage_label 'gap_transition' must be marked True."
        )
    )

class MilestonePlan(BaseModel):
    global_summary: GlobalSummary
    life_periods: List[LifePeriod] = Field(..., description="List of life stages sorted by `period_date_range.start_date` ascending")

class PlanReviewIssue(BaseModel):
    issue_id: str = Field(..., description="Unique issue identifier")
    severity: Literal["low", "medium", "high", "critical"] = Field(..., description="Issue severity")
    issue_type: str = Field(..., description="General reasonableness issue type")
    affected_period_ids: List[str] = Field(default_factory=list, description="Impacted life periods")
    reason: str = Field(..., description="Why this issue is problematic")
    evidence: List[str] = Field(default_factory=list, description="Concrete supporting evidence")


class PeriodContentRefresh(BaseModel):
    """LLM output: refreshed content fields for a single period after stage_label/title patch."""
    dominant_theme: str = Field(..., description="The core organizing logic and dominant theme of this stage (must be semantically consistent with the new stage_label and title)")
    developmental_tasks: List[str] = Field(..., description="Developmental tasks that need to be accomplished in this stage (3-5 items)")
    stage_goals: List[str] = Field(..., description="What goals the working self tends to organize around in this stage (3-5 items)")
    salient_pressures: List[str] = Field(..., description="Typical pressures faced in this stage (2-4 items)")
    salient_opportunities: List[str] = Field(..., description="Opportunity windows that converge toward the target persona (2-4 items)")
    likely_transition_triggers: List[str] = Field(..., description="Events most likely to push this stage into the next stage (1-3 items)")

    # ── Stage type tags (synced when stage_label/title changes) ──
    is_education_stage: bool = Field(False, description="Re-evaluate based on refreshed stage_label and title")
    is_work_stage: bool = Field(False, description="Re-evaluate based on refreshed stage_label and title")
    is_transition_stage: bool = Field(False, description="Re-evaluate based on refreshed stage_label and title")


class PlanPatchAction(BaseModel):
    patch_type: Literal[
        "update_start_date",
        "update_end_date",
        "update_title",
        "update_stage_label",
        "update_transition_anchor",
        "update_is_education_stage",
        "update_is_work_stage",
        "update_is_transition_stage",
        "update_dominant_theme",
        "update_developmental_tasks",
        "update_stage_goals",
        "update_salient_pressures",
        "update_salient_opportunities",
        "update_likely_transition_triggers",
    ] = Field(..., description="Supported local patch type")
    period_id: str = Field(..., description="Target period id")
    field_path: str = Field(..., description="Target field path within the plan")
    new_value: Any = Field(..., description="Replacement value")
    rationale: str = Field(..., description="Why this local patch should fix the issue")


class PlanReviewReport(BaseModel):
    status: Literal["pass", "needs_patch", "needs_regeneration"] = Field(..., description="Review verdict")
    issues: List[PlanReviewIssue] = Field(default_factory=list, description="Detected issues")
    patches: List[PlanPatchAction] = Field(default_factory=list, description="Suggested local patches")
    review_summary: str = Field("", description="High-level review summary")


class PeriodJudgement(BaseModel):
    """Structured verdict for a single period from the Judge stage."""
    period_id: str = Field(..., description="Target period id")
    verdict: Literal["pass", "rewrite", "split", "merge", "delete"] = Field(
        ...,
        description=(
            "pass: period is correct. "
            "rewrite: content needs regeneration (dates unchanged). "
            "split: period spans qualitatively different phases and should be split. "
            "merge: period should be merged with an adjacent period (too short / semantically redundant). "
            "delete: period should not exist (contradicts persona pathway SKIP, or is redundant)."
        ),
    )
    reason: str = Field(..., description="Why this verdict was chosen")
    instruction: str = Field(
        "",
        description=(
            "Specific action instruction. "
            "rewrite: what to change (e.g. 'stage_label should be X, title should reflect Y'). "
            "split: 'split at YYYY-MM-DD into phase A and phase B because ...'. "
            "merge: 'merge with LP2 because both are semantically redundant pre-school periods'. "
            "delete: 'this period contradicts SKIP marker in persona pathway'. "
            "pass: empty."
        ),
    )
    split_point: Optional[str] = Field(
        None,
        description="Only used when verdict=split. The split-point date in ISO format (YYYY-MM-DD).",
    )
    merge_with_prev: bool = Field(
        True,
        description=(
            "Only used when verdict=merge. "
            "True = merge with the previous period (default). "
            "False = merge with the next period."
        ),
    )
    coherence_with_next: str = Field(
        "",
        description="Assessment of coherence between this period and the next already-reviewed period.",
    )


class PlanJudgementReport(BaseModel):
    """Complete output of the Judge stage — one judgement per period."""
    judgements: List[PeriodJudgement] = Field(
        ...,
        description="One PeriodJudgement per period, ordered from last period to first (reverse).",
    )
    global_assessment: str = Field(
        "",
        description="High-level assessment of the entire plan's structural quality.",
    )


class PlanDurationIssue(BaseModel):
    """A single duration-related issue identified by LLM-based validation."""
    period_id: str = Field(..., description="The period_id with the issue")
    issue_type: Literal[
        "too_short_for_content",
        "too_short_for_education_stage",
        "extreme_adjacent_imbalance",
        "statistical_outlier",
        "other",
    ] = Field(..., description="Type of duration issue")
    severity: Literal["low", "medium", "high"] = Field(..., description="Issue severity")
    description: str = Field(..., description="Human-readable description of the issue")
    suggestion: str = Field("", description="Suggested fix direction")


class PlanDurationValidationReport(BaseModel):
    """LLM output: duration reasonableness validation for the entire plan."""
    is_valid: bool = Field(
        ...,
        description=(
            "True if all period durations are reasonable given the persona's "
            "social context, education system, and life trajectory. "
            "False if any period has a problematic duration."
        ),
    )
    issues: List[PlanDurationIssue] = Field(
        default_factory=list,
        description="List of duration issues found. Empty if is_valid=True.",
    )
    summary: str = Field(
        "",
        description="One-line summary of the duration validation result.",
    )


# ==========================================
# CBQA (Causal Backpropagation QA) Data Structures
# ==========================================

class CausalAttribution(BaseModel):
    """Attribution of one validation failure to an upstream pipeline stage."""
    failure_id: str = Field(..., description="Identifier for the validation failure, e.g. 'LP7_too_short'")
    failure_description: str = Field(..., description="Description of the validation failure")
    attributed_stage_id: str = Field(
        ...,
        description=(
            "The pipeline stage that is the root cause. "
            "One of: 'step_0a' (Social Context), 'step_0b' (Persona Pathway), "
            "'step_4' (Transition Hints), 'step_7' (Plan Generation)"
        ),
    )
    attribution_reasoning: str = Field(..., description="Why this stage is identified as the root cause")
    correction_signal: str = Field(
        ...,
        description=(
            "Specific correction instruction for the attributed stage. "
            "Must be concrete, e.g. 'undergrad_graduation should be 2020-06-30 "
            "(1998+22=2020), not 2019-06-30'"
        ),
    )
    confidence: Literal["high", "medium", "low"] = Field("medium", description="Confidence in this attribution")


class ErrorAttributionReport(BaseModel):
    """Output of the CBQA Error Attribution Agent."""
    attributions: List[CausalAttribution] = Field(
        ..., description="List of causal attributions, one per validation failure"
    )
    summary: str = Field("", description="One-line summary of the attribution analysis")
    recommended_re_execution_stages: List[str] = Field(
        default_factory=list,
        description=(
            "Ordered list of pipeline stage IDs that should be re-executed. "
            "e.g. ['step_4', 'step_7'] means re-run Transition Hints then Plan Generation"
        ),
    )


class PlanValidationReport(BaseModel):
    is_valid: bool = Field(..., description="Whether the plan passes general consistency checks")
    risk_level: Literal["low", "medium", "high"] = Field(..., description="Risk level")
    key_issues: List[str] = Field(default_factory=list, description="Key issues identified")
    recommendations: List[str] = Field(default_factory=list, description="Suggested fix directions")

class TransitionDateHint(BaseModel):
    transition_key: str = Field(..., description="Transition point identifier, e.g. phd_graduation / first_job_entry")
    transition_label: str = Field(..., description="Human-readable name for the transition point")
    anchor_date: str = Field(..., description="Transition anchor date, ISO format YYYY-MM-DD")
    confidence: Literal["low", "medium", "high"] = Field(..., description="Confidence level of this date inference")
    is_hard_constraint: bool = Field(False, description="Whether this should be treated as a hard constraint for stage boundaries")
    rationale: str = Field(..., description="Which clues from the input this date was derived from")

class InferredTemporalConstraints(BaseModel):
    current_role_start_date: Optional[str] = Field(None, description="Current role start date (YYYY-MM-DD), can be empty if not reliably inferred")
    pre_current_transition_anchor_date: Optional[str] = Field(None, description="Key transition anchor date before the current role (YYYY-MM-DD), e.g. graduation or key turning point")
    transition_semantic_hint: Literal["general", "graduation"] = Field("general", description="Transition anchor semantic hint")
    rationale: str = Field("", description="Basis for this constraint inference")

class TransitionDateHints(BaseModel):
    summary: str = Field("", description="One-sentence summary of the key transition date set")
    transition_dates: List[TransitionDateHint] = Field(default_factory=list, description="Key transition dates that need special attention in the simulation")
    inferred_temporal_constraints: InferredTemporalConstraints = Field(default_factory=InferredTemporalConstraints, description="Temporal constraints normalized from transition dates by the first LLM step")


# ==========================================
# Social Context Inference Data Structures
# ==========================================

class EducationStage(BaseModel):
    """A single stage in the education system of the inferred social context."""
    stage_name: str = Field(..., description="Education stage identifier, e.g. 'primary_school', 'undergraduate', 'doctoral'")
    typical_entry_age: int = Field(..., description="Typical age at which students enter this stage")
    typical_duration_years: int = Field(..., description="Typical duration in years")
    is_mandatory: bool = Field(False, description="Whether this stage is part of compulsory education")
    entry_month: int = Field(
    0,
    description=(
        "Month when the academic year starts (1-12). "
        "MUST be inferred from the country's education system: "
        "9 for Northern Hemisphere (China/UK/USA), 2 for Southern Hemisphere (NZ/Australia), "
        "4 for Japan, 3 for Korea, etc. "
        "0 means not yet set and MUST be overridden."
    )
)
    notes: str = Field("", description="Additional notes, e.g. 'K-12 system', '6-year medical program'")


class CareerPathNorm(BaseModel):
    """Typical career entry norms for the target occupation in the inferred social context."""
    typical_entry_age_min: int = Field(..., description="Minimum typical age for entering this career")
    typical_entry_age_max: int = Field(..., description="Maximum typical age for entering this career")
    typical_prerequisites: List[str] = Field(default_factory=list, description="Typical prerequisites, e.g. ['bachelor degree', 'PhD']")
    notes: str = Field("", description="Additional notes about career path norms")


class SocialInstitution(BaseModel):
    """A social institution that may affect life stage planning (e.g. military service, retirement)."""
    institution_name: str = Field(..., description="Institution identifier, e.g. 'military_service', 'retirement'")
    applies_to: str = Field(..., description="Who this applies to, e.g. 'all_males', 'all_citizens'")
    typical_age_min: int = Field(..., description="Minimum typical age for this institution")
    typical_age_max: int = Field(..., description="Maximum typical age for this institution")
    typical_duration_months: int = Field(0, description="Typical duration in months (0 if not applicable)")
    is_mandatory: bool = Field(False, description="Whether this is mandatory")
    notes: str = Field("", description="Additional notes")


class PersonaSpecificAdjustment(BaseModel):
    """An adjustment to the typical social context rules based on persona_brief_text."""
    adjustment_type: str = Field(..., description="Type of adjustment, e.g. 'direct_phd_admission', 'child_prodigy', 'gap_year'")
    description: str = Field(..., description="Description of the adjustment")
    affected_stages: List[str] = Field(default_factory=list, description="Which education/career stages are affected")
    rationale: str = Field("", description="Why this adjustment is needed based on persona_brief_text")


class SocialContextProfile(BaseModel):
    """
    Complete social context profile inferred from persona characteristics.
    Used as constraints for life period planning, transition date inference, and plan review.
    """
    country: str = Field(..., description="Country or region code")
    birth_era: str = Field(..., description="Birth era descriptor, e.g. '1990s', '2000s'")
    education_system: List[EducationStage] = Field(..., description="Ordered list of education stages from earliest to latest")
    career_path_norms: CareerPathNorm = Field(..., description="Career entry norms for the target occupation")
    social_institutions: List[SocialInstitution] = Field(default_factory=list, description="Relevant social institutions (military service, retirement, etc.)")
    persona_specific_adjustments: List[PersonaSpecificAdjustment] = Field(default_factory=list, description="Adjustments based on persona_brief_text")
    confidence: Literal["high", "medium", "low"] = Field("medium", description="Overall confidence in the inferred social context")
    summary: str = Field("", description="One-line summary of the social context")


# ==========================================
# Persona Pathway Inference Data Structures (v2)
# ==========================================

class PathwayDimension(BaseModel):
    """A single dimension of the inferred life pathway."""
    dimension: str = Field(
        ...,
        description="The life dimension, e.g., 'education', 'career', "
                    "'social_institution', 'family'"
    )
    pathway_type: str = Field(
        ...,
        description="The inferred pathway type for this dimension, "
                    "e.g., 'direct_phd', 'standard_linear', 'career_switch', "
                    "'military_exempt', 'standard_family'"
    )
    key_stages: List[str] = Field(
        default_factory=list,
        description="Ordered list of key stages/milestones in this dimension, "
                    "e.g., ['primary_school(6y)', 'junior_secondary(3y)', "
                    "'senior_secondary(3y)', 'undergraduate(4y)', 'doctoral(5y)']"
    )
    deviations_from_typical: List[str] = Field(
        default_factory=list,
        description="How this pathway differs from the typical one. "
                    "Use deviation type prefix: SKIP/INSERT/EXTEND/SHORTEN/"
                    "REORDER/PARALLEL/SPLIT/INTERRUPT_RESUME/MERGE. "
                    "e.g., 'SKIP: No independent master stage (direct PhD)'"
    )
    confidence: Literal["high", "medium", "low"] = Field(
        "medium",
        description="Confidence in this inference. 'low' means insufficient "
                    "signals — defaulting to typical pathway"
    )
    inference_basis: str = Field(
        "",
        description="What persona_brief_text signals led to this inference, "
                    "including both explicit mentions and notable absences"
    )


class SuggestedPeriod(BaseModel):
    """A single suggested life period in the period plan.

    Used by InferredPersonaPathway.suggested_periods to guide backward generation.
    Covers all persona types: students, career professionals, retirees, etc.
    """
    stage_key: str = Field(
        ...,
        description=(
            "Stage identifier matching the education system stage_name or a custom label. "
            "e.g. 'early_childhood', 'primary_school', 'secondary_school_lower', "
            "'undergraduate', 'early_career', 'mid_career', 'gap_transition', 'retirement'"
        )
    )
    label_hint: str = Field(
        ...,
        description=(
            "Human-readable label hint for this period. "
            "For education stages, include position info: "
            "e.g. 'Primary school Years 1-3 (foundation)', "
            "'Primary school Years 4-6 (consolidation)', "
            "'Secondary school Years 9-11 (NCEA lower)', "
            "'Undergraduate Year 1-2 (exploration)', "
            "'Undergraduate Year 3-4 (specialization)'. "
            "For non-education stages: 'Early career entry (years 1-3)', "
            "'Mid-career leadership phase', 'Active retirement (years 1-5)', etc."
        )
    )
    approx_start: str = Field(
        ...,
        description=(
            "Approximate start date YYYY-MM (year-month only, not day). "
            "Derived from SocialContextProfile education timeline anchors "
            "(birth_date + typical_entry_age + duration)."
        )
    )
    approx_end: str = Field(
        ...,
        description="Approximate end date YYYY-MM (year-month only, not day)"
    )
    stage_position_hint: Optional[str] = Field(
        None,
        description=(
            "A hint describing where this period falls within its parent stage. "
            "For education stages: grade range, e.g. 'Year 4-6 of 6', 'Year 1-2 of 4'. "
            "For career stages: phase description, e.g. 'early career (years 1-3)', "
            "'mid-career leadership phase', 'pre-retirement wind-down'. "
            "For family stages: 'young children phase', 'empty nest phase'. "
            "For retirement: 'active retirement', 'late retirement'. "
            "None if the stage is short (<2 years) or has no meaningful sub-phases."
        )
    )
    consolidation_rationale: str = Field(
        "",
        description=(
            "Why these years/months are grouped into one period rather than split further. "
            "e.g. 'Years 1-3 share the same developmental theme (foundation building) "
            "with no significant qualitative shift', "
            "'Single year due to major transition event (NCEA Level 3 + university application)', "
            "'Career years 1-5 grouped as early exploration before first promotion'"
        )
    )


class InferredPersonaPathway(BaseModel):
    """
    The actual life pathway inferred for this specific persona.
    Output of Step 0b. PRIMARY reference for Plan Generation.
    """
    dimensions: List[PathwayDimension] = Field(
        ...,
        description="One entry per life dimension (education, career, etc.)"
    )
    overall_rationale: str = Field(
        ...,
        description="Overall rationale for the inferred pathway"
    )
    persona_brief_signals: List[str] = Field(
        default_factory=list,
        description="Key signals from persona_brief_text: "
                    "prefix with EXPLICIT/ABSENT/INFERRED"
    )
    suggested_periods: List[SuggestedPeriod] = Field(
        default_factory=list,
        description=(
            "Ordered list of suggested life periods, from EARLIEST to LATEST. "
            "This is the PRIMARY reference for backward generation — "
            "the backward loop MUST generate exactly these periods (one per entry). "
            "Each entry specifies the stage, approximate dates, position hint, "
            "and why years are grouped this way. "
            "Generated by combining SocialContextProfile rules with persona_brief_text signals. "
            "MUST cover the full life span from birth to reference_date with no gaps."
        )
    )


# ==========================================
# Participant Pool Data Structures
# ==========================================

class DateOfBirth(BaseModel):
    """Structured date-of-birth for a participant."""
    year: int = Field(..., description="Birth year, e.g. 2000")
    month: int = Field(..., description="Birth month, 1-12")
    day: int = Field(..., description="Birth day, 1-31")


class LocationInfo(BaseModel):
    """Geographic location (aligned with PersonaInputSchema LocationInfo)."""
    country: str = Field(..., description="Country code or name, e.g. 'china', 'uk', 'us', 'japan'")
    province: Optional[str] = Field(None, description="Province or region")
    city: Optional[str] = Field(None, description="City name")


class SelfSystemAnchor(BaseModel):
    """Value anchor (aligned with PersonaInputSchema SelfSystemAnchor)."""
    core_values_schwartz_top3: Optional[List[Literal[
        "self_direction", "stimulation", "hedonism", "achievement",
        "power", "security", "conformity", "tradition", "benevolence", "universalism"
    ]]] = Field(
        None,
        min_length=3,
        max_length=3,
        description="Top 3 Schwartz core values, e.g. ['self_direction', 'benevolence', 'security']"
    )


class InteractionRecord(BaseModel):
    """A single interaction record between a participant and the main character."""
    event_id: str = Field(..., description="ID of the event where this interaction occurred")
    time_period: str = Field(
        ...,
        description=(
            "Time period of this interaction. "
            "For point-in-time events: 'YYYY-MM-DD'. "
            "For period-spanning events: 'YYYY-MM-DD to YYYY-MM-DD'. "
            "For approximate events: 'YYYY-MM' or 'YYYY'. "
            "Examples: '2019-02-01', '2019-02-01 to 2021-01-31', '2019-02'"
        )
    )
    date: Optional[str] = Field(
        None,
        description=(
            "Representative date for recency/sorting calculations (YYYY-MM-DD). "
            "For point-in-time events: same as time_period. "
            "For period-spanning events: the END date of the period (for recency accuracy). "
            "Auto-derived from time_period if not explicitly set."
        )
    )
    summary: str = Field(..., description="Brief summary of what happened in this interaction")
    emotional_tone: Optional[str] = Field(None, description="Dominant emotional tone, e.g. 'warm', 'tense', 'neutral'")


class Participant(BaseModel):
    """
    Full participant profile.

    Field names are aligned with PersonaInputSchema in definition.py.
    Every participant (including the target) shares the same schema so that
    downstream modules can treat them uniformly.
    """

    # ── Identity ─────────────────────────────────────────────────
    participant_id: str = Field(..., description="Unique identifier, e.g. 'P_TARGET', 'P_001'")
    role: Literal[
        "target", "family", "friend", "colleague",
        "mentor", "acquaintance", "stranger", "romantic_partner"
    ] = Field(..., description="Relationship role relative to the target persona")

    # ── Basic info (Phase-1 LLM output) ──────────────────────────
    date_of_birth: Optional[DateOfBirth] = Field(None, description="Participant's date of birth")
    relationship_towards_the_main_character: str = Field(
        default="", description="Natural-language description of the relationship with the main character"
    )
    persona_name_text: str = Field(default="", description="Display name of this participant")
    persona_brief_text: str = Field(
        default="",
        description="Overall persona description (used as fallback / general reference)"
    )
    initial_persona_brief_text: str = Field(
        default="",
        description=(
            "Persona background at the simulation start time. "
            "Includes age, occupation, education, personality traits at that point. "
            "Generated once during initialization and never changed afterwards."
        ),
    )
    current_persona_brief_text: str = Field(
        default="",
        description=(
            "Real-time persona background reflecting the character's current state "
            "during simulation. Initially identical to initial_persona_brief_text, "
            "then updated as events unfold."
        ),
    )
    target_persona_brief_text: str = Field(
        default="",
        description=(
            "Persona background at the simulation end time. "
            "Describes the expected final state including target age, occupation, "
            "education, personality traits. Generated once during initialization."
        ),
    )
    appear_period: str = Field(
        default="LP_UNKNOWN",
        description="The period_id (from test_plan life_periods) when this participant first appears"
    )

    # ── Period-level current state (populated by P1d cache) ──
    target_occupation_group_current: Optional[str] = Field(
        default=None,
        description=(
            "Occupation category at the CURRENT simulation period's start date. "
            "Populated from persona_current_state_cache.json. "
            "null if not yet working/studying."
        ),
    )
    target_education_level_current: Optional[str] = Field(
        default=None,
        description=(
            "Highest completed education level (ISCED 0-8) at the CURRENT simulation period. "
            "Populated from persona_current_state_cache.json."
        ),
    )
    self_system_anchor_current: Optional[dict] = Field(
        default=None,
        description=(
            "Core values at the CURRENT simulation period. "
            "Populated from persona_current_state_cache.json. "
            "Dict with key 'core_values_schwartz_top3'."
        ),
    )

    # ── Geographic (aligned with PersonaInputSchema) ─────────────
    growing_up_location: Optional[LocationInfo] = Field(None, description="Where this participant primarily grew up")
    current_living_location: Optional[LocationInfo] = Field(None, description="Current city of residence")

    # ── Occupation & Education (aligned with PersonaInputSchema) ─
    target_occupation_group: Optional[Literal[
        "student", "manager_executive",
        "professional_finance_law_consulting", "professional_tech_research",
        "professional_health_education", "office_admin_support",
        "sales_customer_service", "service_hospitality_retail",
        "skilled_trades_technical_ops", "manual_logistics_transport",
        "public_service_military", "self_employed_creator",
        "retired", "unemployed", "homemaker"
    ]] = Field(None, description="Simplified occupation group code")

    # ISCED 2011 mapping:
    #   "0" = Early childhood education    "1" = Primary education
    #   "2" = Lower secondary education    "3" = Upper secondary education
    #   "4" = Post-secondary non-tertiary  "5" = Short-cycle tertiary
    #   "6" = Bachelor's or equivalent     "7" = Master's or equivalent
    #   "8" = Doctoral or equivalent
    target_education_level: Optional[Literal[
        "0", "1", "2", "3", "4", "5", "6", "7", "8"
    ]] = Field(None, description="ISCED 2011 level code")

    # ── Psychological & Social (aligned with PersonaInputSchema) ─
    self_system_anchor: Optional[SelfSystemAnchor] = Field(None, description="Personality / value anchor")
    childhood_primary_residential_context: Optional[Literal[
        "cities", "towns_and_suburbs", "rural_areas"
    ]] = Field(None, description="Childhood residential context (DEGURBA)")
    primary_language: Optional[Literal["en"]] = Field(None, description="Primary language code")
    working_language: Optional[List[Literal["en"]]] = Field(None, description="Working language code list")
    childhood_living_arrangement: Optional[Literal[
        "two_married_parents", "two_cohabiting_parents", "single_parent", "other"
    ]] = Field(None, description="Childhood living arrangement")
    gender_identity_code: Optional[Literal[
        "1_male", "2_female", "3_non_binary", "4_other", "Z_not_stated"
    ]] = Field(None, description="Gender identity code")
    caregiver_bond_pbi: Optional[Literal[
        "optimal_parenting", "affectionate_constraint",
        "affectionless_control", "neglectful_parenting"
    ]] = Field(None, description="Caregiver bond type (PBI)")
    childhood_adversity_aceiq_13: Optional[List[str]] = Field(
        None, description="Childhood adversity items (ACE-IQ 13)"
    )
    adult_attachment_rq4cat: Optional[Literal[
        "secure", "fearful", "preoccupied", "dismissing"
    ]] = Field(None, description="Adult attachment style (RQ 4-category)")

    # ── Interaction history ──────────────────────────────────────
    interactions_history_with_the_main_character: List[InteractionRecord] = Field(
        default_factory=list,
        description="Chronological list of interactions with the main character (initialized empty)"
    )

    # ── Benchmark extensions ─────────────────────────────────────
    persona_extensions: Optional[Dict[str, Any]] = Field(
        None,
        description=(
            "Benchmark-specific extension attributes preserved from the input persona data. "
            "This is schema-free — each benchmark populates its own structure. "
            "Rendered into prompts via persona_extensions_formatter. "
            "Semantically equivalent to extra_context in persona_to_json."
        ),
    )


# ── LLM Structured Output Models for Multi-Phase Initialization ──

class Phase1BasicInfo(BaseModel):
    """Phase-1 LLM output: basic identity information for a participant."""
    date_of_birth: DateOfBirth = Field(..., description="Participant's date of birth")
    relationship_towards_the_main_character: str = Field(
        ..., description="Natural-language description of the relationship with the main character"
    )
    persona_name_text: str = Field(..., description="Full name of this participant")
    gender_identity_code: Optional[str] = Field(
        None, description="Gender identity code: 1_male / 2_female / 3_non_binary / 4_other / Z_not_stated"
    )
    role: Optional[str] = Field(
        None,
        description=(
            "Relationship role relative to the target persona. "
            "One of: family, friend, colleague, mentor, acquaintance, stranger, romantic_partner"
        ),
    )
    persona_brief_text: str = Field(
        ..., description="One-paragraph overall persona description covering personality, background, and role in the main character's life"
    )


class Phase1ParticipantList(BaseModel):
    """Phase-1 LLM output: a list of participants to bootstrap."""
    participants: List[Phase1BasicInfo] = Field(
        ..., description="List of participants with basic identity information"
    )


class Phase2TemporalBriefs(BaseModel):
    """
    Phase-2 LLM output: three temporal persona briefs for a single participant.

    Each brief describes the participant at a different point in the simulation
    timeline, providing a complete temporal dimension for the character.
    """
    initial_persona_brief_text: str = Field(
        ...,
        description=(
            "Persona background at the simulation START time. "
            "Describe the character's age, occupation/student status, education level, "
            "personality traits, and relationship with the main character at that point."
        ),
    )
    target_persona_brief_text: str = Field(
        ...,
        description=(
            "Persona background at the simulation END time. "
            "Describe the character's expected age, occupation, education level, "
            "personality traits, and relationship with the main character at that point."
        ),
    )


class Phase3FullProfile(BaseModel):
    """Phase-3 LLM output: gender_identity_code only.

    All other extended profile fields (location, occupation, education, etc.)
    have been removed. Only gender_identity_code is inferred by LLM since it
    may not be determinable from Phase-1 output alone.
    """
    gender_identity_code: Optional[str] = None


# Phase4SingleMemory and Phase4InitialMemories removed:
# interactions_history_with_the_main_character is always initialized empty.
# No pre-simulation memories are generated.


class Phase5ConsistencyResult(BaseModel):
    """Phase-5 LLM output: timeline consistency check result for a single participant."""
    has_issues: bool = Field(
        ...,
        description="Whether any timeline inconsistencies were found",
    )
    issues_found: List[str] = Field(
        default_factory=list,
        description=(
            "List of specific inconsistency issues found. "
            "Each item describes one issue, e.g. 'target age 56 does not match DOB 1970 and end date 2026'"
        ),
    )
    corrected_initial_persona_brief_text: Optional[str] = Field(
        None,
        description=(
            "Corrected initial_persona_brief_text if issues were found in the original. "
            "None if no correction needed."
        ),
    )
    corrected_target_persona_brief_text: Optional[str] = Field(
        None,
        description=(
            "Corrected target_persona_brief_text if issues were found in the original. "
            "None if no correction needed."
        ),
    )
    corrected_persona_brief_text: Optional[str] = Field(
        None,
        description=(
            "Corrected persona_brief_text (overall brief) if issues were found. "
            "None if no correction needed."
        ),
    )


class Phase6TargetInitialBrief(BaseModel):
    """
    Phase-6 LLM output: the target's initial_persona_brief_text only.

    A lightweight model that asks the LLM to produce just the protagonist's
    status description at simulation start time.  Unlike Phase2TemporalBriefs
    this does NOT require target_persona_brief_text, reducing failure rate.
    """
    initial_persona_brief_text: str = Field(
        ...,
        description=(
            "Persona background of the protagonist at the simulation START time. "
            "Describe the character's age/birth status, family environment, "
            "parents' current occupations and states, and living situation at that point."
        ),
    )


# ==========================================
# v7: Backward Sequential Generation Data Structures
# ==========================================

class BackwardPeriodOutput(BaseModel):
    """LLM output for a single backward-generated period."""
    start_date: str = Field(
        ...,
        description=(
            "Period start date in YYYY-MM-DD format. "
            "Refer to the social context education system rules to decide. "
            "If this is the very first period of life, set to birth_date."
        ),
    )
    stage_label: str = Field(
        ...,
        description=(
            "Semantic stage label in snake_case, e.g. 'early_childhood', "
            "'primary_school', 'undergraduate_exploration', 'phd_research_pivot', "
            "'career_entry_adaptation'. Gap/transition periods MUST use 'gap_transition'."
        ),
    )
    title: str = Field(..., description="A concise title summarizing this life period")
    dominant_theme: str = Field(..., description="The core organizing logic and dominant theme of this period")
    developmental_tasks: List[str] = Field(..., description="Development tasks for this period (3-5 items)")
    stage_goals: List[str] = Field(..., description="Goals the working self organizes around (3-5 items)")
    salient_pressures: List[str] = Field(..., description="Typical pressures faced in this period (2-4 items)")
    salient_opportunities: List[str] = Field(..., description="Opportunities for convergence toward target persona (2-4 items)")
    likely_transition_triggers: List[str] = Field(..., description="Events most likely to push into the next period (1-3 items)")
    is_education_stage: bool = Field(False, description="Whether this period involves education/learning activities")
    is_work_stage: bool = Field(False, description="Whether this period involves work/career activities")
    is_transition_stage: bool = Field(False, description="Whether this period is a transition/gap period")
    is_first_period: bool = Field(
        False,
        description=(
            "Set to True if you believe this period already covers the earliest "
            "part of life (from birth). When the age at end of this period is "
            "very young, this should typically be True."
        ),
    )


class FixImpactAnalysis(BaseModel):
    """Result of impact propagation analysis for plan fixes."""
    directly_affected: List[str] = Field(
        default_factory=list,
        description="Period IDs with issues found directly by review",
    )
    propagation_affected: List[str] = Field(
        default_factory=list,
        description="Period IDs affected by fixing the direct issues (cascading)",
    )
    fix_strategy: Literal["isolated", "cascading", "full_regen"] = Field(
        "isolated",
        description="Fix strategy: isolated (1-2 periods), cascading (3-5), full_regen (>50%)",
    )
    fix_groups: List[List[str]] = Field(
        default_factory=list,
        description="Ordered groups of period IDs to fix together",
    )
