"""
P1.5 Milestone Planner — Prior-Knowledge-Driven High-Res Detail Pre-planning
==============================================================================

Identifies key milestones for each life period and generates coarse-grained
skeletons that guide downstream P2 (event generation) and P3 (high-res
simulation).

Pipeline position: runs after P1c (Key Life Path Cache), before P2.

Two-step LLM flow:
  Step 1: Global milestone identification (1 LLM call covering all periods)
  Step 2: Skeleton generation per milestone (parallel LLM calls)

When no LLM client is provided (smoke-test mode), a deterministic rule-engine
fallback produces skeletons from the key_life_path_cache.
"""

from __future__ import annotations

import json
import logging
import os
from datetime import date
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field as PydanticField

logger = logging.getLogger(__name__)


# ═══════════════════════════════════════════════════════════════
# Data Models
# ═══════════════════════════════════════════════════════════════

class MilestoneHRSkeleton(BaseModel):
    """Pre-planned high-res event skeleton for a key milestone."""

    period_id: str = PydanticField(..., description="Parent period id, e.g. 'LP5'")
    milestone_type: str = PydanticField(
        ...,
        description="One of: stage_transition, achievement, decision, crisis",
    )
    milestone_name: str = PydanticField(
        ..., description="Short name, e.g. 'College Entrance Exam', 'PhD Defense'"
    )

    # Coarse-grained skeleton (generated by P1.5)
    summary_hint: str = PydanticField(
        ..., description="Event summary hint (100-200 chars, NOT the final summary)"
    )
    motivation_hint: str = PydanticField(
        default="", description="Trigger / motivation hint"
    )
    outcome_hint: str = PydanticField(
        default="", description="Expected outcome hint"
    )
    value_for_target: str = PydanticField(
        default="", description="Value for the protagonist"
    )

    # Temporal constraints
    expected_date_range: str = PydanticField(
        ..., description="Expected date range, e.g. '2016-06-07 to 2016-06-08'"
    )
    expected_duration_hours: float = PydanticField(
        default=4.0, description="Expected duration in hours"
    )

    # Narrative constraints (passed to Step 1b outline and P3 simulation)
    turning_point_hint: str = PydanticField(
        default="", description="Key turning point hint"
    )
    emotional_arc_hint: str = PydanticField(
        default="", description="Emotional arc hint"
    )
    mandatory_beats: List[str] = PydanticField(
        default_factory=list,
        description="Key beats that MUST be covered in P3 simulation",
    )

    # Coherence constraints (passed to Step 1a low-res generation)
    low_res_coherence_constraints: str = PydanticField(
        default="",
        description="Constraints for low-res events in the same period",
    )

    # Tier and priority
    simulation_tier: int = PydanticField(
        default=1,
        description="1=deep (full P3), 2=standard (short P3), 3=skeleton-only (no P3)",
    )
    priority_score: float = PydanticField(
        default=0.5, description="Priority score 0-1"
    )


class MilestoneIdentification(BaseModel):
    """LLM output for Step 1: identify one milestone per period."""

    period_id: str = PydanticField(..., description="Period id")
    milestone_name: str = PydanticField(..., description="Short milestone name")
    milestone_type: str = PydanticField(
        ..., description="stage_transition / achievement / decision / crisis"
    )
    expected_date_range: str = PydanticField(
        ..., description="Expected date range"
    )
    reason: str = PydanticField(..., description="Why this is the key milestone")
    priority_score: float = PydanticField(
        ..., description="Priority score 0-1"
    )


class MilestoneIdentificationOutput(BaseModel):
    """LLM output for Step 1: all milestones."""

    milestones: List[MilestoneIdentification] = PydanticField(
        ..., description="One milestone per period (skip periods with no clear milestone)"
    )


class SkeletonGenerationOutput(BaseModel):
    """LLM output for Step 2: skeleton for a single milestone."""

    summary_hint: str = PydanticField(
        ..., description="Event summary hint (100-200 chars)"
    )
    motivation_hint: str = PydanticField(default="", description="Trigger hint")
    outcome_hint: str = PydanticField(default="", description="Outcome hint")
    value_for_target: str = PydanticField(default="", description="Value for target")
    turning_point_hint: str = PydanticField(
        default="", description="Key turning point"
    )
    emotional_arc_hint: str = PydanticField(
        default="", description="Emotional arc"
    )
    mandatory_beats: List[str] = PydanticField(
        default_factory=list, description="Must-cover beats (2-4 items)"
    )
    low_res_coherence_constraints: str = PydanticField(
        default="", description="Coherence constraints for surrounding low-res events"
    )
    expected_duration_hours: float = PydanticField(
        default=4.0, description="Expected duration in hours"
    )


# ═══════════════════════════════════════════════════════════════
# Tier Assignment
# ═══════════════════════════════════════════════════════════════

def compute_simulation_tier(
    am_weight: float,
    priority_score: float,
) -> int:
    """Assign simulation tier based on AM weight and priority.

    Tier 1 (deep):          AM > 0.5 AND priority > 0.7
    Tier 2 (standard):      AM > 0.3 OR priority > 0.5
    Tier 3 (skeleton-only): everything else
    """
    if am_weight > 0.5 and priority_score > 0.7:
        return 1
    if am_weight > 0.3 or priority_score > 0.5:
        return 2
    return 3


def _estimate_am_weight_for_period(
    period: Dict[str, Any],
    birth_date_str: str,
    reference_date_str: str,
) -> float:
    """Estimate AM weight for a period using midpoint age."""
    try:
        birth = date.fromisoformat(birth_date_str)
        ref = date.fromisoformat(reference_date_str)
        dr = period.get("period_date_range", {})
        start = date.fromisoformat(dr.get("start_date", birth_date_str))
        end = date.fromisoformat(dr.get("end_date", reference_date_str))
        mid = start + (end - start) / 2
        years_ago = (ref - mid).days / 365.25
        current_age = (ref - birth).days / 365.25
        if current_age <= 0:
            return 0.0
        # Simplified AM weight: recency-based
        normalised = max(0.0, 1.0 - years_ago / current_age)
        return round(min(1.0, normalised), 3)
    except (ValueError, TypeError):
        return 0.3


# ═══════════════════════════════════════════════════════════════
# Rule-Engine Fallback (no LLM needed)
# ═══════════════════════════════════════════════════════════════

def _rule_engine_milestones(
    life_plan: Dict[str, Any],
    key_life_path_cache: Dict[str, Any],
    birth_date_str: str,
    reference_date_str: str,
) -> Dict[str, MilestoneHRSkeleton]:
    """Deterministic milestone extraction from key_life_path_cache.

    Looks for stage transitions, exams, and key events to pick the most
    important milestone per period.
    """
    periods = life_plan.get("life_periods", [])
    result: Dict[str, MilestoneHRSkeleton] = {}

    # Build year→period mapping
    year_to_period: Dict[int, str] = {}
    for p in periods:
        dr = p.get("period_date_range", {})
        try:
            s_year = int(dr.get("start_date", "")[:4])
            e_year = int(dr.get("end_date", "")[:4])
            for y in range(s_year, e_year + 1):
                year_to_period[y] = p["period_id"]
        except (ValueError, TypeError):
            pass

    # Collect candidate milestones from key_life_path_cache
    candidates: Dict[str, List[Dict[str, Any]]] = {}
    for year_str, year_data in key_life_path_cache.items():
        try:
            year = int(year_str)
        except (ValueError, TypeError):
            continue
        period_id = year_to_period.get(year)
        if not period_id:
            continue

        # Exams (high priority)
        exams = year_data.get("exams_this_year", [])
        if isinstance(exams, list):
            for exam in exams:
                name = exam.get("exam_name", "")
                if not name:
                    continue
                priority = 0.9 if name in ("高考", "中考", "Gaokao", "College Entrance Exam", "Zhongkao") else 0.6
                candidates.setdefault(period_id, []).append({
                    "name": name,
                    "type": "stage_transition" if name in ("高考", "中考", "Gaokao", "College Entrance Exam", "Zhongkao") else "achievement",
                    "date_range": exam.get("date_range", f"{year}-06"),
                    "description": exam.get("description", name),
                    "priority": priority,
                    "year": year,
                })

        # Key events (stage transitions)
        events = year_data.get("key_events", [])
        if isinstance(events, list):
            for evt in events:
                name = evt.get("event_name", "")
                is_transition = evt.get("is_stage_transition", False)
                if not name:
                    continue
                # Graduation events are important milestones
                if "毕业" in name or "graduation" in name.lower():
                    priority = 0.7
                elif is_transition:
                    priority = 0.5
                else:
                    priority = 0.3
                candidates.setdefault(period_id, []).append({
                    "name": name,
                    "type": "stage_transition" if is_transition else "achievement",
                    "date_range": evt.get("date", f"{year}-06"),
                    "description": evt.get("description", name),
                    "priority": priority,
                    "year": year,
                })

    # Also check likely_transition_triggers from life_plan periods
    period_lookup = {p["period_id"]: p for p in periods}
    for period_id, p in period_lookup.items():
        triggers = p.get("likely_transition_triggers", [])
        for trigger in triggers:
            trigger_lower = trigger.lower()
            # Boost priority for well-known milestones mentioned in triggers
            if any(kw in trigger_lower for kw in ["高考", "答辩", "毕业", "入职", "面试", "gaokao", "defense", "graduation", "onboarding", "interview"]):
                for cand in candidates.get(period_id, []):
                    if any(kw in cand["name"] for kw in ["高考", "答辩", "毕业", "gaokao", "defense", "graduation"]):
                        cand["priority"] = min(1.0, cand["priority"] + 0.1)

    # Select best candidate per period
    for period_id, cands in candidates.items():
        if not cands:
            continue
        best = max(cands, key=lambda c: c["priority"])

        am_weight = _estimate_am_weight_for_period(
            period_lookup.get(period_id, {}),
            birth_date_str,
            reference_date_str,
        )
        tier = compute_simulation_tier(am_weight, best["priority"])

        result[period_id] = MilestoneHRSkeleton(
            period_id=period_id,
            milestone_type=best["type"],
            milestone_name=best["name"],
            summary_hint=best["description"],
            motivation_hint="",
            outcome_hint="",
            value_for_target="",
            expected_date_range=best["date_range"],
            expected_duration_hours=4.0,
            turning_point_hint="",
            emotional_arc_hint="",
            mandatory_beats=[],
            low_res_coherence_constraints="",
            simulation_tier=tier,
            priority_score=best["priority"],
        )

    return result


# ═══════════════════════════════════════════════════════════════
# Main Entry Point
# ═══════════════════════════════════════════════════════════════

async def generate_milestone_plan(
    life_plan: Dict[str, Any],
    persona_config: Dict[str, Any],
    output_dir: str,
    llm_client=None,
    key_life_path_cache: Optional[Dict[str, Any]] = None,
) -> Dict[str, MilestoneHRSkeleton]:
    """Generate the milestone HR pre-plan.

    Steps:
    1. Load key_life_path_cache (from file or parameter)
    2. Rule engine: extract candidate milestones from cache + life_plan
    3. (Optional) LLM Step 1: global milestone identification
    4. (Optional) LLM Step 2: skeleton generation per milestone (parallel)
    5. Assign simulation tiers
    6. Save to milestone_plan.json

    Args:
        life_plan: Complete life plan dict from P1a.
        persona_config: Persona configuration dict.
        output_dir: Directory to save milestone_plan.json.
        llm_client: Optional AsyncLLMClient. If None, uses rule-engine only.
        key_life_path_cache: Optional pre-loaded cache. If None, loads from file.

    Returns:
        Dict mapping period_id -> MilestoneHRSkeleton
    """
    # Step 1: Load key_life_path_cache
    if key_life_path_cache is None:
        cache_path = os.path.join(output_dir, "year_enrichment_key_life_path_cache.json")
        if os.path.isfile(cache_path):
            with open(cache_path, "r", encoding="utf-8") as f:
                key_life_path_cache = json.load(f)
            logger.info(f"[P1.5] Loaded key_life_path_cache from {cache_path}")
        else:
            key_life_path_cache = {}
            logger.warning(f"[P1.5] No key_life_path_cache found at {cache_path}")

    # Extract birth_date and reference_date
    global_summary = life_plan.get("global_summary", {})
    birth_date_str = (
        persona_config.get("derived_birth_date")
        or persona_config.get("birth_date_str", "")
        or global_summary.get("timeline_anchor", {}).get("derived_birth_date", "")
    )
    reference_date_str = (
        life_plan.get("reference_date")
        or persona_config.get("reference_date", "")
        or date.today().isoformat()
    )

    if not birth_date_str:
        logger.warning("[P1.5] No birth date found, cannot generate milestone plan")
        return {}

    # Step 2: Rule engine extraction
    milestones = _rule_engine_milestones(
        life_plan=life_plan,
        key_life_path_cache=key_life_path_cache,
        birth_date_str=birth_date_str,
        reference_date_str=reference_date_str,
    )
    logger.info(
        f"[P1.5] Rule engine identified {len(milestones)} milestones: "
        f"{list(milestones.keys())}"
    )

    # Step 3 & 4: LLM enrichment (optional)
    if llm_client is not None:
        try:
            milestones = await _llm_enrich_milestones(
                milestones=milestones,
                life_plan=life_plan,
                persona_config=persona_config,
                llm_client=llm_client,
                birth_date_str=birth_date_str,
                reference_date_str=reference_date_str,
            )
        except Exception as e:
            logger.warning(
                f"[P1.5] LLM enrichment failed, using rule-engine milestones: {e}"
            )

    # Step 5: Log tier distribution
    tier_counts = {1: 0, 2: 0, 3: 0}
    for m in milestones.values():
        tier_counts[m.simulation_tier] = tier_counts.get(m.simulation_tier, 0) + 1
    logger.info(
        f"[P1.5] Tier distribution: "
        f"Tier1(deep)={tier_counts[1]}, "
        f"Tier2(standard)={tier_counts[2]}, "
        f"Tier3(skeleton)={tier_counts[3]}"
    )

    # Step 6: Save to file
    os.makedirs(output_dir, exist_ok=True)
    plan_path = os.path.join(output_dir, "milestone_plan.json")
    serializable = {
        pid: skel.model_dump() for pid, skel in milestones.items()
    }
    with open(plan_path, "w", encoding="utf-8") as f:
        json.dump(serializable, f, ensure_ascii=False, indent=2)
    logger.info(f"[P1.5] Saved milestone plan ({len(milestones)} milestones) to {plan_path}")

    return milestones


async def _llm_enrich_milestones(
    milestones: Dict[str, MilestoneHRSkeleton],
    life_plan: Dict[str, Any],
    persona_config: Dict[str, Any],
    llm_client,
    birth_date_str: str,
    reference_date_str: str,
) -> Dict[str, MilestoneHRSkeleton]:
    """Use LLM to enrich milestone skeletons with narrative details.

    Step 1: Global milestone re-ranking (may add/remove milestones)
    Step 2: Skeleton enrichment per milestone (parallel)
    """
    import asyncio

    periods = life_plan.get("life_periods", [])
    persona_brief = persona_config.get("persona_brief_text", "")

    # ── Step 1: Global milestone identification ──
    periods_summary = []
    for p in periods:
        dr = p.get("period_date_range", {})
        periods_summary.append({
            "period_id": p.get("period_id"),
            "title": p.get("title"),
            "dominant_theme": p.get("dominant_theme"),
            "stage_goals": p.get("stage_goals", []),
            "likely_transition_triggers": p.get("likely_transition_triggers", []),
            "date_range": f"{dr.get('start_date', '')} to {dr.get('end_date', '')}",
            "rule_engine_milestone": milestones.get(p["period_id"], {
                "milestone_name": "(none)", "priority_score": 0
            }) if isinstance(milestones.get(p["period_id"]), dict) else (
                milestones[p["period_id"]].model_dump()
                if p["period_id"] in milestones else {"milestone_name": "(none)"}
            ),
        })

    system_prompt = (
        "You are a life trajectory analysis expert. Based on a person's complete life plan, "
        "identify the most critical milestone event for each stage.\n\n"
        "Selection criteria (by priority):\n"
        "1. Stage transition nodes (e.g., college entrance exam, graduation, first job)\n"
        "2. Key decision points in life direction (e.g., choosing a major, career change)\n"
        "3. Major validation moments of ability/identity (e.g., thesis publication, defense)\n"
        "4. Major family / relationship transitions (e.g., marriage, divorce, widowhood, "
        "birth of child, remarriage)\n"
        "5. Core identity exploration moments (e.g., coming out, religious questioning or "
        "conversion, racial identity formation, first same-sex relationship, confronting "
        "discrimination, disability advocacy milestone) — equally important as career "
        "milestones for personas whose brief explicitly names identity traits\n"
        "6. Significant adversity or hardship events (e.g., job loss, divorce, bereavement, "
        "financial crisis) that fundamentally reshape the persona's worldview or behavior\n\n"
        "Exclusion criteria:\n"
        "- Routine procedural events (e.g., enrollment, registration, moving dorms)\n"
        "- Repetitive events (e.g., weekly meetings, regular classes)\n"
        "- Uneventful incidents without dramatic turning points\n\n"
        "IMPORTANT: Family / relationship events (marriage, divorce, widowhood, birth of "
        "child, remarriage, etc.) are NEVER 'routine' or 'procedural'. They represent "
        "major qualitative life shifts and MUST be selected as milestones when present in "
        "a period, even if the period seems otherwise unremarkable. Do NOT exclude them "
        "under the 'Routine procedural events' or 'Repetitive events' criteria.\n\n"
        "IMPORTANT: For personas with explicit identity traits (e.g., homosexual, Atheist, "
        "Black, transgender, deaf), identity exploration events are NEVER 'routine'. They "
        "represent defining moments in the character's self-understanding and MUST be "
        "selected as milestones when present in a period.\n\n"
        "Select at most 1 milestone per period. Infancy/toddler periods (0-3 years) can be skipped."
    )

    user_prompt = (
        f"## Persona Brief\n{persona_brief}\n\n"
        f"## Life Stage Overview\n{json.dumps(periods_summary, ensure_ascii=False, indent=2)}\n\n"
        "For each period, select at most 1 most critical milestone and provide a priority_score (0-1)."
    )

    try:
        identification: MilestoneIdentificationOutput = await llm_client.generate_structured(
            prompt=user_prompt,
            response_model=MilestoneIdentificationOutput,
            system_prompt=system_prompt,
            temperature=0.0,
            task_type="p1_5_milestone_identification",
        )

        # Merge LLM identifications with rule-engine milestones
        period_lookup = {p["period_id"]: p for p in periods}
        for mid in identification.milestones:
            pid = mid.period_id
            if pid not in period_lookup:
                continue
            am_weight = _estimate_am_weight_for_period(
                period_lookup[pid], birth_date_str, reference_date_str
            )
            tier = compute_simulation_tier(am_weight, mid.priority_score)

            if pid in milestones:
                # Update existing
                milestones[pid].milestone_name = mid.milestone_name
                milestones[pid].milestone_type = mid.milestone_type
                milestones[pid].expected_date_range = mid.expected_date_range
                milestones[pid].priority_score = mid.priority_score
                milestones[pid].simulation_tier = tier
            else:
                # Add new
                milestones[pid] = MilestoneHRSkeleton(
                    period_id=pid,
                    milestone_type=mid.milestone_type,
                    milestone_name=mid.milestone_name,
                    summary_hint=mid.reason,
                    expected_date_range=mid.expected_date_range,
                    simulation_tier=tier,
                    priority_score=mid.priority_score,
                )

        logger.info(f"[P1.5] LLM Step 1 complete: {len(identification.milestones)} milestones identified")

    except Exception as e:
        logger.warning(f"[P1.5] LLM Step 1 failed: {e}")

    # ── Step 2: Skeleton enrichment (parallel) ──
    async def enrich_one(pid: str, skel: MilestoneHRSkeleton) -> None:
        period = next((p for p in periods if p["period_id"] == pid), None)
        if not period:
            return

        sys_prompt = (
            'Generate a coarse-grained event skeleton based on key milestones in the life plan.\n'
            'The skeleton only needs to provide "what must happen" and "what the key turning point is",\n'
            'no need for precise times, participant lists, or scene details (those are generated at runtime).'
        )
        usr_prompt = (
            f"## Persona Brief\n{persona_brief}\n\n"
            f"## Stage Information\n"
            f"- period_id: {pid}\n"
            f"- title: {period.get('title', '')}\n"
            f"- dominant_theme: {period.get('dominant_theme', '')}\n"
            f"- stage_goals: {json.dumps(period.get('stage_goals', []), ensure_ascii=False)}\n\n"
            f"## Milestone\n"
            f"- name: {skel.milestone_name}\n"
            f"- type: {skel.milestone_type}\n"
            f"- expected_date: {skel.expected_date_range}\n\n"
            f"Please generate the event skeleton for this milestone."
        )

        try:
            enriched: SkeletonGenerationOutput = await llm_client.generate_structured(
                prompt=usr_prompt,
                response_model=SkeletonGenerationOutput,
                system_prompt=sys_prompt,
            temperature=0.0,
            task_type="p1_5_skeleton_generation",
            )
            skel.summary_hint = enriched.summary_hint or skel.summary_hint
            skel.motivation_hint = enriched.motivation_hint
            skel.outcome_hint = enriched.outcome_hint
            skel.value_for_target = enriched.value_for_target
            skel.turning_point_hint = enriched.turning_point_hint
            skel.emotional_arc_hint = enriched.emotional_arc_hint
            skel.mandatory_beats = enriched.mandatory_beats
            skel.low_res_coherence_constraints = enriched.low_res_coherence_constraints
            skel.expected_duration_hours = enriched.expected_duration_hours
        except Exception as e:
            logger.warning(f"[P1.5] LLM Step 2 failed for {pid}: {e}")

    tasks = [enrich_one(pid, skel) for pid, skel in milestones.items()]
    if tasks:
        await asyncio.gather(*tasks)
        logger.info(f"[P1.5] LLM Step 2 complete: {len(tasks)} skeletons enriched")

    return milestones


def load_milestone_plan(output_dir: str) -> Dict[str, MilestoneHRSkeleton]:
    """Load a previously saved milestone_plan.json."""
    plan_path = os.path.join(output_dir, "milestone_plan.json")
    if not os.path.isfile(plan_path):
        return {}
    with open(plan_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return {
        pid: MilestoneHRSkeleton(**skel_data)
        for pid, skel_data in data.items()
    }
